#pragma once

#include "port/settings.h"

#include <string>
#include <string_view>

namespace partyboard::ui {

inline std::string ui_translate(std::string_view text)
{
    if (partyboard::getSettings().game.language.getValue() != partyboard::GameLanguage::French) {
        return std::string(text);
    }
    struct Entry { std::string_view source; std::string_view translated; };
    static constexpr Entry entries[] = {
        {"Compiling shaders", "Compilation des shaders"}, {"Preparing...", "Préparation…"},
        {"This only happens once. The result is kept for future launches.", "Cela n’arrive qu’une seule fois. Le résultat est conservé pour les prochains lancements."},
        {"Settings", "Paramètres"}, {"Achievements", "Succès"}, {"Quit", "Quitter"},
        {"Play", "Jouer"}, {"Play Online", "Jouer en ligne"}, {"Select Disc Image", "Sélectionner l’image disque"}, {"Prelaunch", "Avant le lancement"},
        {"Online mode", "Mode en ligne"}, {"PartyBoardOnline.exe is missing or could not be started.", "PartyBoardOnline.exe est absent ou ne peut pas être démarré."},
        {"The online lobby could not be opened.", "Le salon en ligne n'a pas pu être ouvert."},
        {"Account and saves (QR code)", "Compte et sauvegardes (QR code)"},
        {"In CubeShelf on your PC: My profile, Play on a phone, Show the QR code. Both devices must be on the same Wi-Fi.", "Dans CubeShelf sur ton PC : Mon profil, Jouer sur téléphone, Afficher le QR code. Les deux appareils doivent être sur le même Wi-Fi."},
        {"Scan: get my account and my saves", "Scanner : récupérer mon compte et mes sauvegardes"},
        {"Scan: send my saves to the PC", "Scanner : envoyer mes sauvegardes au PC"},
        {"Paste the code shown under the QR code", "Coller le code affiché sous le QR code"},
        {"The clipboard holds no CubeShelf code (it starts with CSL1:).", "Le presse-papiers ne contient pas de code CubeShelf (il commence par CSL1:)."},
        {"Code pasted. Choose what to do: get my account and my saves, or send my saves to the PC.", "Code collé. Choisis : récupérer mon compte et mes sauvegardes, ou envoyer mes sauvegardes au PC."},
        {"The QR code transfer could not start.", "Le transfert par QR code n'a pas pu démarrer."},
        {"Getting your account and your saves from the PC...", "Récupération de ton compte et de tes sauvegardes depuis le PC..."},
        {"Sending your saves to the PC...", "Envoi de tes sauvegardes vers le PC..."},
        {"The transfer failed.", "Le transfert a échoué."},
        {"Saves sent to the PC.", "Sauvegardes envoyées au PC."},
        {"Your account is on this device.", "Ton compte est sur cet appareil."},
        {"The PC had no Mario Party 4 save to send.", "Le PC n'avait aucune sauvegarde de Mario Party 4 à envoyer."},
        {"{} save file(s) received from the PC. They replace this device's at the next start (the old ones are kept in save-backups).", "{} fichier(s) de sauvegarde reçu(s) du PC. Ils remplacent ceux de cet appareil au prochain démarrage (les anciens sont gardés dans save-backups)."},
        {"Later", "Plus tard"}, {"Restart now", "Redémarrer maintenant"},
        {"<br/>This screen refreshes at up to {} Hz.", "<br/>Cet écran monte jusqu'à {} Hz."},
        {"Welcome to Party Board", "Bienvenue dans Party Board"},
        {"Choose a preset to get started. You can change any setting later from the Settings menu.", "Choisissez un préréglage pour commencer. Vous pourrez le modifier plus tard dans les paramètres."},
        {"Classic", "Classique"}, {"Enhancements disabled to match the GameCube version.", "Améliorations désactivées pour correspondre à la version GameCube."},
        {"Quality of life tweaks, our recommended way to play!", "Améliorations pratiques, notre façon recommandée de jouer !"},
        {"Verifying disc image", "Vérification de l’image disque"}, {"Opening disc image...", "Ouverture de l’image disque…"}, {"Cancelling...", "Annulation…"},
        {"No disc image found.", "Aucune image disque trouvée."}, {"Pending restart.", "Redémarrage en attente."}, {"Disc ready.", "Image disque prête."},
        {"Rev", "Rév."}, {"Disc hash mismatch.", "Le hash de l’image disque ne correspond pas."}, {"Disc not verified.", "Image disque non vérifiée."}, {"Disc unavailable.", "Image disque indisponible."},
        {"The selected disc image could not be validated.", "L’image disque sélectionnée n’a pas pu être validée."},
        {"Unable to read the selected file.", "Impossible de lire le fichier sélectionné."},
        {"The selected file is not a valid disc image.", "Le fichier sélectionné n’est pas une image disque valide."},
        {"The selected game is not supported by Party Board. Choose a USA or European Mario Party 4 GameCube disc image.", "Le jeu sélectionné n’est pas pris en charge par Party Board. Choisissez une image disque GameCube de Mario Party 4 en version américaine ou européenne."},
        {"The Japanese version of Mario Party 4 is not supported yet. Please use the USA or European version.", "La version japonaise de Mario Party 4 n’est pas encore prise en charge. Utilisez la version américaine ou européenne."},
        {"This version of Mario Party 4 is not supported yet. Please use the USA or European version.", "Cette version de Mario Party 4 n’est pas encore prise en charge. Utilisez la version américaine ou européenne."},
        {"Disc verification was canceled. Party Board cannot guarantee the selected disc image is compatible.", "La vérification de l’image disque a été annulée. Party Board ne peut pas garantir sa compatibilité."},
        {"The selected disc image did not pass hash verification. It may be corrupt or modified.", "L’image disque sélectionnée n’a pas passé la vérification du hash. Elle est peut-être corrompue ou modifiée."},
        {"The selected disc image is valid.", "L’image disque sélectionnée est valide."},
        {"Disc verification warning", "Avertissement de vérification de l’image disque"}, {"Continue anyway", "Continuer quand même"},
        {"Disc verification error", "Erreur de vérification de l’image disque"}, {"Apply Options", "Appliquer les options"},
        {"Restart later", "Redémarrer plus tard"}, {"Restart now", "Redémarrer maintenant"},
        {"A restart is required to apply selected options.<br/><br/>Restart now to apply them immediately?", "Un redémarrage est nécessaire pour appliquer les options sélectionnées.<br/><br/>Redémarrer maintenant pour les appliquer ?"},
        {"A restart is required to apply selected options.<br/><br/>Close and reopen Party Board to apply them.", "Un redémarrage est nécessaire pour appliquer les options sélectionnées.<br/><br/>Fermez puis rouvrez Party Board pour les appliquer."},
        {"Display", "Affichage"}, {"Resolution", "Résolution"}, {"Input", "Entrées"}, {"Controller", "Manette"},
        {"Tools", "Outils"}, {"Gameplay", "Jeu"}, {"Speedrunning", "Course rapide"}, {"Cheats", "Triches"},
        {"Minigames", "Mini-jeux"}, {"Boards", "Plateaux"}, {"Interface", "Interface"}, {"Party Board", "Party Board"},
        {"Language", "Langue"}, {"English", "Anglais"}, {"German", "Allemand"}, {"French", "Français"},
        {"Spanish", "Espagnol"}, {"Italian", "Italien"}, {"Disc Image", "Image disque"},
        {"Open Data Folder", "Ouvrir le dossier de données"}, {"Notifications", "Notifications"}, {"Types", "Types"},
        {"Actions", "Actions"}, {"Select All", "Tout sélectionner"}, {"Select None", "Tout désélectionner"},
        {"Challenge", "Défi"}, {"Collection", "Collection"}, {"Minigame", "Mini-jeu"}, {"Misc", "Divers"}, {"Glitched", "Glitchés"},
        {"Clear?", "Effacer ?"}, {"Unlocked", "Déverrouillé"}, {"Locked", "Verrouillé"}, {"unlocked", "déverrouillés"},
        {"Configure Controller", "Configurer la manette"}, {"Allow Background Input", "Autoriser les entrées en arrière-plan"},
        {"Turbo Key", "Touche turbo"}, {"Speedrun Mode", "Mode course rapide"}, {"Unlock All Minigames", "Déverrouiller tous les mini-jeux"},
        {"Unlock Bowser's Gnarly Party", "Déverrouiller la fête infernale de Bowser"}, {"Frame Rate", "Fréquence d’images"},
        {"Lock 4:3 Aspect Ratio", "Verrouiller le format 4:3"}, {"Adaptive Widescreen HUD", "HUD écran large adaptatif"},
        {"Internal Resolution", "Résolution interne"}, {"Shadow Resolution", "Résolution des ombres"},
        {"Pause On Focus Lost", "Pause si la fenêtre perd le focus"}, {"Skip Party Board Main Menu", "Ignorer le menu principal Party Board"},
        {"Skip Game Boot Sequence", "Ignorer le démarrage du jeu"}, {"Off", "Désactivées"}, {"All", "Toutes"}, {"Some", "Certaines"},
        {"Clear All Achievements", "Effacer tous les succès"}, {"Are you sure?", "Confirmer ?"}, {"No controller assigned", "Aucune manette assignée"},
        {"to open menu", "pour ouvrir le menu"}, {"Configure controller port 1 in Settings.", "Configurez la manette du port 1 dans les paramètres."}, {"Quit Party Board", "Quitter Party Board"},
        {"Unsaved progress will be lost.", "La progression non sauvegardée sera perdue."}, {"Cancel", "Annuler"}, {"Confirm", "Confirmer"},
        {"No controllers detected", "Aucune manette détectée"}, {"No controller selected", "Aucune manette sélectionnée"},
        {"Buttons", "Boutons"}, {"D-Pad", "Croix directionnelle"}, {"Analog", "Analogique"}, {"Digital", "Numérique"},
        {"Control Stick", "Stick principal"}, {"C Stick", "Stick C"}, {"Sensor", "Capteur"}, {"Mouse", "Souris"},
        {"Not bound", "Non attribué"}, {"Unknown", "Inconnu"}, {"Return", "Retour"}, {"Reset to default", "Réinitialiser"},
        {"3-finger tap or", "Touchez avec 3 doigts ou"}, {"Press F1 or", "Appuyez sur F1 ou"}, {"(none)", "(aucune)"},
        {"Online Lobby", "Salon en ligne"}, {"Your Party Board lobby", "Votre salon PartyBoard"}, {"Nickname", "Pseudo"}, {"Player", "Joueur"},
        {"Choose a nickname of 1 to 24 characters, on a single line.", "Choisissez un pseudo de 1 à 24 caractères, sans retour à la ligne."},
        {"The name the other players see in the lobby.", "Le nom que les autres joueurs voient dans le salon."},
        {"Every player needs the same disc image: Mario Party 4 USA. The whole file is checked before joining.", "Chaque joueur doit avoir la même image disque : Mario Party 4 USA. Le fichier complet est vérifié avant de rejoindre."},
        {"Players", "Joueurs"}, {"How many players the lobby waits for, you included. Only the host chooses.", "Nombre de joueurs attendus dans le salon, vous compris. Seul l’hôte choisit."},
        {"Create a lobby", "Créer un salon"}, {"Create the lobby, then send the invitation to your friends. Only you can start the game.", "Créez le salon, puis envoyez l’invitation à vos amis. Vous seul pourrez lancer le jeu."},
        {"Join a lobby", "Rejoindre un salon"}, {"Invitation", "Invitation"},
        {"The invitation starts with PB4. The host copies it from their lobby, on a PC or a phone.", "L’invitation commence par PB4. L’hôte la copie depuis son salon, sur PC ou sur téléphone."},
        {"Paste invitation", "Coller l’invitation"}, {"Paste the invitation your friend sent you.", "Collez l’invitation envoyée par votre ami."},
        {"Join", "Rejoindre"}, {"Join your friend's lobby. The host starts the game for everyone.", "Rejoignez le salon de votre ami. L’hôte lance la partie pour tout le monde."},
        {"Lobby", "Salon"}, {"Leave lobby", "Quitter le salon"}, {"Leave the lobby and clear the invitation.", "Quitter le salon et effacer l’invitation."},
        {"Disc ready. Create a lobby or paste your friend's invitation.", "Disque prêt. Créez un salon ou collez l’invitation de votre ami."},
        {"Choose your disc to get started.", "Choisissez votre disque pour commencer."},
        {"Hosting from this device is not available yet: the online connection is still being ported. Create the lobby on a PC for now.", "Héberger depuis cet appareil n’est pas encore disponible : la connexion en ligne est en cours de portage. Créez le salon sur un PC pour l’instant."},
        {"Joining from this device is not available yet: the online connection is still being ported.", "Rejoindre depuis cet appareil n’est pas encore disponible : la connexion en ligne est en cours de portage."},
        {"Paste your friend's invitation first.", "Collez d’abord l’invitation de votre ami."},
        {"Valid invitation for a lobby of {} players.", "Invitation valide pour un salon de {} joueurs."},
        {"The clipboard is empty.", "Le presse-papiers est vide."}, {"Invitation pasted. Press Join.", "Invitation collée. Appuyez sur Rejoindre."},
        {"Invitation is valid.", "L’invitation est valide."},
        {"This invitation comes from an older version of Party Board. Both players need the same version.", "Cette invitation vient d’une version plus ancienne de Party Board. Les deux joueurs doivent avoir la même version."},
        {"This invitation has expired. The host must create a new lobby.", "Cette invitation a expiré. L’hôte doit recréer un salon."},
        {"The invitation is incomplete. Copy all of it from your friend's device.", "L’invitation est incomplète. Copiez-la entièrement depuis l’appareil de votre ami."},
        {"CubeShelf profile", "Profil CubeShelf"}, {"Refresh now", "Actualiser maintenant"}, {"Forget this profile", "Oublier ce profil"}, {"Forget", "Oublier"},
        {"This device will no longer see your friends. Your PC and your friends are not affected; you can import the profile again at any time.", "Cet appareil ne verra plus tes amis. Ton PC et tes amis ne sont pas concernés ; tu pourras réimporter le profil à tout moment."},
        {"Import your CubeShelf profile", "Importer ton profil CubeShelf"}, {"Passphrase", "Mot de passe"},
        {"The passphrase you chose in CubeShelf when exporting the profile.", "Le mot de passe choisi dans CubeShelf au moment de l’export."},
        {"Import from a file", "Importer depuis un fichier"}, {"Import from the clipboard", "Importer depuis le presse-papiers"},
        {"Choose the .cubeshelf-profile file exported by CubeShelf and copied to this device.", "Choisis le fichier .cubeshelf-profile exporté par CubeShelf et copié sur cet appareil."},
        {"If you sent yourself the content of the file (it starts with CSP1-), copy it, then import it from here.", "Si tu t’es envoyé le contenu du fichier (il commence par CSP1-), copie-le puis importe-le d’ici."},
        {"On your PC, open CubeShelf, then My profile, Play on a phone, and export your profile. This device will then see your friends and their invitations; your PC keeps publishing your presence.", "Sur ton PC, ouvre CubeShelf, puis Mon profil, Jouer sur téléphone, et exporte ton profil. Cet appareil verra alors tes amis et leurs invitations ; ton PC continue de publier ta présence."},
        {"No file was chosen.", "Aucun fichier choisi."}, {"Type the passphrase first.", "Saisis d’abord le mot de passe."}, {"Importing...", "Import en cours…"},
        {"Profile imported.", "Profil importé."}, {"This is not a profile exported by CubeShelf.", "Ce n’est pas un profil exporté par CubeShelf."},
        {"Wrong passphrase, or the file was modified.", "Mot de passe incorrect, ou fichier modifié."},
        {"This profile comes from a CubeShelf version this Party Board does not read.", "Ce profil vient d’une version de CubeShelf que ce Party Board ne lit pas."},
        {"The key in this profile is unreadable.", "La clé de ce profil est illisible."},
        {"The profile is unreadable: the file was modified or cut short.", "Profil illisible : le fichier a été modifié ou tronqué."},
        {"That invitation is no longer valid: the lobby was closed or has expired.", "Cette invitation n’est plus valable : le salon a été fermé ou a expiré."},
        {"Screen Controller", "Manette à l’écran"}, {"Screen Controller Opacity", "Opacité de la manette à l’écran"},
        {"Automatic", "Automatique"}, {"Always", "Toujours"}, {"Never", "Jamais"},
        {"A GameCube controller drawn on the screen, for playing on a phone or a tablet. Automatic shows it on touch screens whenever no gamepad is plugged into port 1.", "Une manette GameCube dessinée à l’écran, pour jouer sur téléphone ou tablette. En automatique, elle s’affiche sur les écrans tactiles dès qu’aucune manette n’est branchée sur le port 1."},
        {"How visible the screen controller is over the game.", "Visibilité de la manette à l’écran par-dessus le jeu."},
        {"Update Available", "Mise à jour disponible"}, {"Update", "Mettre à jour"}, {"Download", "Télécharger"}, {"Later", "Plus tard"}, {"Retry", "Réessayer"},
        {"Check for Updates", "Rechercher les mises à jour"}, {"Check Now", "Rechercher maintenant"},
        {"Look for a newer build on GitHub when Party Board starts. When there is one, the home screen offers to download it; nothing is downloaded without asking.", "Cherche une version plus récente sur GitHub au démarrage de Party Board. S’il y en a une, l’écran d’accueil propose de la télécharger ; rien n’est téléchargé sans votre accord."},
        {"Look for a newer build on GitHub now. The answer shows on the home screen, under the version.", "Cherche tout de suite une version plus récente sur GitHub. La réponse s’affiche sur l’écran d’accueil, sous la version."},
        {"Checking GitHub for an update...", "Recherche d’une mise à jour sur GitHub…"},
        {"Party Board is up to date (build {}).", "Party Board est à jour (build {})."},
        {"Build {} is available.", "La build {} est disponible."},
        {"Open the downloaded file to install the update.", "Ouvrez le fichier téléchargé pour installer la mise à jour."},
        {"Party Board build {} is available. This phone has build {}.", "La build {} de Party Board est disponible. Ce téléphone a la build {}."},
        {"What changed:", "Ce qui change :"},
        {"The download opens in your browser: open the file once it is downloaded to install the update. Your saves and settings are kept.", "Le téléchargement s’ouvre dans votre navigateur : ouvrez le fichier une fois téléchargé pour installer la mise à jour. Vos sauvegardes et vos réglages sont conservés."},
        {"Could not open the download.", "Impossible d’ouvrir le téléchargement."},
        {"Could not reach GitHub.", "Impossible de joindre GitHub."},
        {"GitHub did not send the update manifest.", "GitHub n’a pas envoyé le manifeste de mise à jour."},
        {"The update manifest on GitHub is invalid.", "Le manifeste de mise à jour sur GitHub est invalide."},
    };
    for (const auto &entry : entries) if (entry.source == text) return std::string(entry.translated);
    return std::string(text);
}

} // namespace partyboard::ui
