#ifndef DATA_MAKE_NUM_EFFECT_H
#define DATA_MAKE_NUM_EFFECT_H

#include "datadir_enum.h"

enum {
    EFFECT_ANM_star = DATA_MAKE_NUM(DATADIR_EFFECT, 0),
    EFFECT_ANM_glow = DATA_MAKE_NUM(DATADIR_EFFECT, 1),
    EFFECT_ANM_dust = DATA_MAKE_NUM(DATADIR_EFFECT, 2),
    EFFECT_ANM_smoke = DATA_MAKE_NUM(DATADIR_EFFECT, 3),
    EFFECT_ANM_circle = DATA_MAKE_NUM(DATADIR_EFFECT, 4),
    EFFECT_ANM_hatena = DATA_MAKE_NUM(DATADIR_EFFECT, 5),
    EFFECT_ANM_danger = DATA_MAKE_NUM(DATADIR_EFFECT, 6),
    EFFECT_ANM_bird = DATA_MAKE_NUM(DATADIR_EFFECT, 7),
};

#endif
