param([string]$OutputDirectory = 'build\aexp\RelWithDebInfo')
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
$vs = & $vswhere -latest -prerelease -products '*' -property installationPath
$csc = Join-Path $vs 'MSBuild\Current\Bin\Roslyn\csc.exe'
$output = if ([IO.Path]::IsPathRooted($OutputDirectory)) {
    [IO.Path]::GetFullPath($OutputDirectory)
} else {
    [IO.Path]::GetFullPath((Join-Path $root $OutputDirectory))
}
$source = Join-Path $PSScriptRoot 'online'
New-Item -ItemType Directory -Path $output -Force | Out-Null

# The bridge forwards the game's UDP packets only if it recognises them, and it
# recognises them by exact length and protocol version. Those two numbers live
# in the engine header. When they last changed - 88 to 152 bytes and version 6
# to 7, in "netplay: complete canonical deterministic state hashing" - the C#
# copy was not updated, and the bridge silently dropped every game packet: both
# lobbies connected, the game launched, and each peer sat there until "Aucun
# joueur compatible apres 2 minutes". Generating the constants means the copy
# cannot fall behind again.
$header = Join-Path $root 'include/port/netplay_transport.hpp'
if (-not (Test-Path -LiteralPath $header)) { throw "Missing $header." }
$packetSize = $null
$protocolVersion = $null
foreach ($line in Get-Content $header) {
    if ($line -match 'kNetplayPacketSize\s*=\s*(\d+)') { $packetSize = [int]$Matches[1] }
    if ($line -match 'kProtocolVersion\s*=\s*(\d+)') { $protocolVersion = [int]$Matches[1] }
}
if (-not $packetSize -or -not $protocolVersion) {
    throw "Could not read kNetplayPacketSize / kProtocolVersion from $header."
}
$generated = Join-Path $output 'WireFormat.generated.cs'
@"
// Generated by tools/build_online.ps1 from include/port/netplay_transport.hpp.
// Do not edit: change the header instead and rebuild.
namespace PartyBoardOnline {
static class WireFormat {
    public const int PacketSize = $packetSize;
    public const int ProtocolVersion = $protocolVersion;
    public const byte VersionHigh = (byte)(ProtocolVersion >> 8);
    public const byte VersionLow = (byte)(ProtocolVersion & 0xFF);
}
}
"@ | Set-Content -LiteralPath $generated -Encoding ascii
Write-Output "wire format: $packetSize octets, protocole v$protocolVersion"

& $csc /nologo /target:winexe /platform:x64 /optimize+ /warnaserror+ /langversion:latest "/out:$output\PartyBoardOnline.exe" /reference:System.dll /reference:System.Core.dll /reference:System.Drawing.dll /reference:System.Windows.Forms.dll /reference:System.Xml.dll /reference:Microsoft.CSharp.dll "$source\Connection.cs" "$source\Gateway.cs" "$source\Program.cs" "$source\Lobby.cs" "$source\LobbyForm.cs" "$source\Tests.cs" "$source\Report.cs" "$source\UpdateService.cs" "$generated"
if ($LASTEXITCODE -ne 0) { throw 'Online companion compilation failed.' }
Copy-Item -LiteralPath "$source\PartyBoardOnline.exe.config" -Destination $output -Force

