# Finds a deliberate route to the boards nobody has recorded.
#
# THE IDEA, and it is not mine. Valentin pointed out that a run can pause, quit
# the board through the menu, and go do another one - and that a campaign should
# go looking for the boards never exercised instead of repeating the two that
# are. This is the directed version of that: rather than hoping a random monkey
# wanders onto a new board, take the approach that is KNOWN to work and change
# the one decision that picks the board.
#
# HOW. board-replay.txt reaches Boo's Haunted Bash. Its overlay path says the
# menu (overlay 70) runs from frame 2989 to 5961, and a board list is a cursor:
# a stick pulse dropped inside that window moves the cursor before the confirm
# that follows it. So one pulse is injected at a candidate frame, the run is
# played, and the run itself reports which board it loaded.
#
# Nothing is inferred. The board comes from the overlay path, never from
# GWSystem.board, which is 0 both for "Toad's Midway Madness" and for "no board
# chosen yet" - a distinction the first survey got wrong.
#
#   tools\scan_board_select.ps1 -DiscPath "<iso>"
#   tools\scan_board_select.ps1 -DiscPath "<iso>" -From 3000 -To 5900 -Step 200
#
# Exit codes: 0 a board other than Boo was reached, 1 none was, 2 nothing ran.

param(
    [Parameter(Mandatory = $true)][string]$DiscPath,
    [string]$Prefix = 'work/gen/prefix-w04.txt',
    # The menu window, from the overlay path of the recording the prefix came
    # from: 70@2989 (menu) to 92@5961 (the board). Outside it there is no cursor
    # to move.
    [int]$From = 3000,
    [int]$To = 5900,
    [int]$Step = 290,
    # Which way to push the cursor. Both are tried at each point, because a list
    # can be walked from either end and one direction may be blocked.
    [int]$Magnitude = 72,
    [int]$HoldFrames = 8,
    # Long enough to load a board and take a turn, short enough that a scan of
    # twenty points fits in a night.
    [int]$Seconds = 150,
    [string]$ResultFile = 'work/scan-board-select.md'
)

$ErrorActionPreference = 'Stop'
$projectPath = Split-Path $PSScriptRoot -Parent
function Resolve-ScanPath([string]$path) {
    if ([IO.Path]::IsPathRooted($path)) { return [IO.Path]::GetFullPath($path) }
    return [IO.Path]::GetFullPath((Join-Path $projectPath $path))
}

$python = $null
foreach ($candidate in 'python3', 'python', 'py') {
    $found = Get-Command $candidate -ErrorAction SilentlyContinue
    if ($found) { $python = $found.Source; break }
}
if (-not $python) { Write-Output 'No python interpreter found.'; exit 2 }

$generator = Join-Path $PSScriptRoot 'generate_input.py'
$campaign = Join-Path $PSScriptRoot 'netplay_campaign.ps1'
$prefixPath = Resolve-ScanPath $Prefix
if (-not (Test-Path -LiteralPath $prefixPath)) {
    Write-Output "Missing $prefixPath. Cut one with generate_input.py slice."
    exit 2
}

$boardNames = @{}
foreach ($line in Get-Content (Resolve-ScanPath 'docs/netplay_validation_matrix.md')) {
    if ($line -match '^\|\s*(\d{2})\s*\|\s*`(w\d{2}dll)`\s*\|\s*(\d+)\s*\|\s*([^|]+?)\s*\|') {
        $boardNames[[int]$Matches[3]] = $Matches[4].Trim()
    }
}

$results = @()
$points = @()
for ($frame = $From; $frame -le $To; $frame += $Step) { $points += $frame }

foreach ($frame in $points) {
    foreach ($direction in @(1, -1)) {
        $tag = "scan-$frame-$(if ($direction -gt 0) { 'r' } else { 'l' })"
        $input = Resolve-ScanPath "work/gen/$tag.txt"

        $previous = $ErrorActionPreference
        $ErrorActionPreference = 'Continue'
        try {
            & $python $generator inject $prefixPath --at $frame --frames $HoldFrames `
                --stick-x ($Magnitude * $direction) -o $input 2>&1 | Out-Null
            if ($LASTEXITCODE -ne 0) { throw "inject failed" }
        } catch {
            Write-Output ("  {0}: inject failed" -f $tag)
            $ErrorActionPreference = $previous
            continue
        }

        $manifest = Resolve-ScanPath 'work/scan-scenarios.json'
        $document = @{
            version = 1
            note = 'Generated by scan_board_select.ps1. Not part of the shipped campaign.'
            scenarios = @(@{
                id = $tag
                description = "Approach to Boo with a stick pulse at frame $frame, direction $direction."
                board = 'unknown'; kind = 'replay'
                replay = "work/gen/$tag.txt"
                durationSeconds = $Seconds
                minFrames = 1000
                repeats = 1; netplayDelay = 3; seed = 'recorded'
                coverageSource = 'SCRIPTED'
            })
        }
        [IO.File]::WriteAllText($manifest, ($document | ConvertTo-Json -Depth 8),
            (New-Object Text.UTF8Encoding $false))

        # Out-Null used to eat everything the campaign said, including its
        # refusals. Eighteen probes once reported NO RUN in a row while the
        # campaign was declining each time, in a sentence nobody saw, because a
        # reference recording had changed. Keep the log, and stop the scan on a
        # refusal rather than filling a table with empty rows.
        $campaignLog = Resolve-ScanPath "work/gen/$tag.campaign.log"
        $campaignExit = 0
        try {
            & $campaign -DiscPath $DiscPath -Manifest 'work/scan-scenarios.json' `
                -Scenario $tag -Label $tag -AudioDiagnostics '' 2>&1 |
                Tee-Object -FilePath $campaignLog | Out-Null
            $campaignExit = $LASTEXITCODE
        } catch {
            $campaignExit = 3
            [IO.File]::AppendAllText($campaignLog, "$_`n")
        } finally {
            $ErrorActionPreference = $previous
        }
        if ($campaignExit -eq 3) {
            Write-Output ''
            Write-Output "ARRET: la campagne a refuse de demarrer sur $tag."
            foreach ($line in (Get-Content $campaignLog -ErrorAction SilentlyContinue |
                    Where-Object { $_ -match 'HARNESS FAILURE|REFUS|DIFFERENT|missing' } |
                    Select-Object -First 6)) {
                Write-Output "  $line"
            }
            Write-Output "  journal complet : $campaignLog"
            exit 2
        }

        $dir = Get-ChildItem (Resolve-ScanPath 'work/netplay-campaigns') -Directory -Filter "*-$tag" -ErrorAction SilentlyContinue |
            Select-Object -Last 1
        $board = -1; $name = '(aucun)'; $frames = 0; $result = 'NO RUN'; $reached = ''
        if ($dir) {
            $runFile = Get-ChildItem $dir.FullName -Recurse -Filter 'run.json' -ErrorAction SilentlyContinue | Select-Object -First 1
            if ($runFile) {
                $run = Get-Content $runFile.FullName -Raw | ConvertFrom-Json
                $frames = [int]$run.last_frame
                $result = [string]$run.result
                $path = @()
                if ($run.PSObject.Properties.Name -contains 'overlays') { $path = @($run.overlays) }
                # Every overlay worth naming, so one scan answers two questions:
                # which board, and did this pulse reach the minigame mode at all.
                $interesting = @{ 72 = 'mgmode'; 86 = 'selmenu'; 88 = 'subchrsel'; 3 = 'inst'; 84 = 'result' }
                $seen = New-Object Collections.Generic.List[string]
                foreach ($entryText in $path) {
                    $id = [int](($entryText -split '@')[0])
                    if ($id -ge 89 -and $id -le 97) {
                        $board = [int]$run.board_id
                        if (-not $seen.Contains("board$id")) { $seen.Add("board$id") }
                    } elseif ($interesting.ContainsKey($id)) {
                        if (-not $seen.Contains($interesting[$id])) { $seen.Add($interesting[$id]) }
                    } elseif ($id -ge 13 -and $id -le 75) {
                        if (-not $seen.Contains("mg$id")) { $seen.Add("mg$id") }
                    }
                }
                $reached = ($seen -join ' ')
                if ($board -ge 0 -and $boardNames.ContainsKey($board)) { $name = $boardNames[$board] }
            }
        }
        $results += @{ Frame = $frame; Dir = $direction; Board = $board; Name = $name
                       Frames = $frames; Result = $result; Reached = $reached }
        Write-Output ("  frame {0,5} {1}  ->  board {2,2} {3,-24} [{4}]  ({5} frames, {6})" -f
            $frame, $(if ($direction -gt 0) { 'droite' } else { 'gauche' }), $board, $name, $reached, $frames, $result)
    }
}

$lines = New-Object Collections.Generic.List[string]
function Emit([string]$t) { $lines.Add($t); Write-Output $t }
Emit ''
Emit '# Ou se choisit le plateau, et comment en atteindre un autre'
Emit ''
Emit ("Impulsion de stick injectee dans l'approche connue de Boo, {0} points entre" -f $points.Count)
Emit ("les frames {0} et {1}, dans les deux directions. Le plateau rapporte vient du" -f $From, $To)
Emit "chemin d'overlays, jamais de GWSystem.board."
Emit ''
Emit '| frame | direction | plateau | nom | overlays atteints | frames | resultat |'
Emit '|---|---|---|---|---|---|---|'
foreach ($r in $results) {
    Emit ('| {0} | {1} | {2} | {3} | {4} | {5} | {6} |' -f
        $r.Frame, $(if ($r.Dir -gt 0) { 'droite' } else { 'gauche' }), $r.Board, $r.Name,
        $r.Reached, $r.Frames, $r.Result)
}
$mgMode = @($results | Where-Object { $_.Reached -match 'mgmode|selmenu' })
Emit ''
Emit ("Impulsions ayant atteint le mode mini-jeu : **{0}**" -f $mgMode.Count)
foreach ($r in $mgMode) { Emit ("  - frame {0} {1} : {2}" -f $r.Frame, $(if ($r.Dir -gt 0) { 'droite' } else { 'gauche' }), $r.Reached) }
$boardsFound = @($results | Where-Object { $_.Board -ge 0 } | ForEach-Object { $_.Board } | Sort-Object -Unique)
$new = @($boardsFound | Where-Object { $_ -ne 3 })
Emit ''
Emit ("Plateaux atteints : {0}" -f $(if ($boardsFound.Count) { $boardsFound -join ', ' } else { 'aucun' }))
Emit ("Autres que Boo (board 3) : **{0}**" -f $(if ($new.Count) { $new -join ', ' } else { 'aucun' }))

$target = Resolve-ScanPath $ResultFile
New-Item -ItemType Directory -Path (Split-Path $target -Parent) -Force | Out-Null
[IO.File]::WriteAllLines($target, $lines)
Write-Output ''
Write-Output "ecrit dans $target"

if ($new.Count -gt 0) { exit 0 }
exit 1
