# Asks which boards a monkey can reach on its own, one seed at a time.
#
# WHY THIS EXISTS. Reaching a board needs menu navigation, and until tonight the
# monkey could not navigate at all: it pressed the d-pad, which src/game/pad.c
# masks out of HuPadBtn entirely, so the game never saw a single direction it
# chose. Menus read the analog stick. With that fixed the question becomes
# empirical - can a random monkey get to a board, and which ones - and it is
# answered by trying, not by reasoning.
#
# Each attempt is one seed, driven from BOOT with no approach prefix, given a
# short budget.
#
# WHICH BOARD IT REACHED comes from the OVERLAY PATH, not from board_id, and the
# difference nearly produced a false headline on the very first seed.
# GWSystem.board is 0 before any board has been chosen, and 0 is also the id of
# Toad's Midway Madness - so a run that never left the boot screen reported
# "reached Toad's Midway Madness". The overlay path cannot be ambiguous that
# way: a board overlay appears in it only if the board was actually loaded.
# board_id is still read, and a disagreement between the two is reported rather
# than resolved.
#
#   tools\survey_boards.ps1 -DiscPath "<iso>" -Seeds 3001..3020
#   tools\survey_boards.ps1 -DiscPath "<iso>" -Seeds 3001,3002 -Seconds 600
#
# The table it prints is the answer: seed, board reached, turn, frames.
#
# Exit codes: 0 at least one board was reached, 1 none were, 2 nothing ran.

param(
    [Parameter(Mandatory = $true)][string]$DiscPath,
    [int[]]$Seeds = @(3001, 3002, 3003, 3004, 3005, 3006, 3007, 3008),
    # A recorded approach reaches a board around frame 5961, about 100 seconds.
    # A monkey wandering a menu needs longer, and how much longer is exactly
    # what is unknown - so this is generous rather than tight.
    [int]$Seconds = 300,
    [string]$ResultFile = 'work/survey-boards.md'
)

$ErrorActionPreference = 'Stop'
$projectPath = Split-Path $PSScriptRoot -Parent
function Resolve-SurveyPath([string]$path) {
    if ([IO.Path]::IsPathRooted($path)) { return [IO.Path]::GetFullPath($path) }
    return [IO.Path]::GetFullPath((Join-Path $projectPath $path))
}

# Board id -> name, parsed from the validation matrix so the pairing lives in
# one place only.
$boardNames = @{}
foreach ($line in Get-Content (Resolve-SurveyPath 'docs/netplay_validation_matrix.md')) {
    if ($line -match '^\|\s*(\d{2})\s*\|\s*`(w\d{2}dll)`\s*\|\s*(\d+)\s*\|\s*([^|]+?)\s*\|') {
        $boardNames[[int]$Matches[3]] = $Matches[4].Trim()
    }
}

$manifestPath = Resolve-SurveyPath 'work/survey-scenarios.json'
$campaign = Join-Path $PSScriptRoot 'netplay_campaign.ps1'
$results = @()
$started = Get-Date

foreach ($seed in $Seeds) {
    # One scenario per seed, written fresh. minFrames is deliberately low and
    # minTurns absent: this asks "did it reach a board", not "did it play well",
    # and gating on turns here would throw away the answer.
    $document = @{
        version = 1
        note = 'Generated by survey_boards.ps1. Not part of the shipped campaign.'
        scenarios = @(
            @{
                id = "survey-$seed"
                description = "Monkey from boot, seed $seed, no approach prefix. Asks which board it finds."
                board = 'unknown'
                kind = 'replay'
                replay = "work/gen/survey-$seed.txt"
                durationSeconds = $Seconds
                minFrames = 1000
                repeats = 1
                netplayDelay = 3
                seed = 'generated'
                coverageSource = 'SCRIPTED'
                generated = @{ seed = $seed; frames = ($Seconds * 60 + 600) }
            }
        )
    }
    [IO.File]::WriteAllText($manifestPath, ($document | ConvertTo-Json -Depth 8),
        (New-Object Text.UTF8Encoding $false))

    Write-Output ("--- seed {0} ({1} s budget) ---" -f $seed, $Seconds)
    $previous = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        # The audio lifetime detector is switched OFF for a survey. It reports
        # HARNESS_FAILURE when it never sees a bank released, which is correct
        # for a campaign and wrong here: a run that never leaves the boot screen
        # had no chance to free one, and that is the ANSWER, not a broken
        # harness. The heap and stack detectors stay on - they arm at startup.
        & $campaign -DiscPath $DiscPath -Manifest 'work/survey-scenarios.json' `
            -Scenario "survey-$seed" -Label "survey-$seed" -AudioDiagnostics '' 2>&1 |
            Where-Object { $_ -match 'run 1:|HARNESS' } | ForEach-Object { Write-Output ("    " + $_) }
    } catch {
        Write-Output ("    exception: " + $_.Exception.Message)
    } finally {
        $ErrorActionPreference = $previous
    }

    # The answer comes from the run record, never from the log.
    $dir = Get-ChildItem (Resolve-SurveyPath 'work/netplay-campaigns') -Directory -Filter "*-survey-$seed" -ErrorAction SilentlyContinue |
        Select-Object -Last 1
    $entry = @{ Seed = $seed; Board = -1; Name = '(aucun)'; Turn = -1; Frames = 0
                Result = 'NO RUN'; Minigames = @(); Overlays = 0; Note = '' }
    if ($dir) {
        $runFile = Get-ChildItem $dir.FullName -Recurse -Filter 'run.json' -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($runFile) {
            $run = Get-Content $runFile.FullName -Raw | ConvertFrom-Json
            $entry.Turn = [int]$run.board_turn
            $entry.Frames = [int]$run.last_frame
            $entry.Result = [string]$run.result
            if ($run.PSObject.Properties.Name -contains 'minigames_played') { $entry.Minigames = @($run.minigames_played) }

            # A board overlay in the path is the evidence. 89-97 are the boards.
            $path = @()
            if ($run.PSObject.Properties.Name -contains 'overlays') { $path = @($run.overlays) }
            $entry.Overlays = $path.Count
            $boardOverlay = -1
            foreach ($entryText in $path) {
                $id = [int](($entryText -split '@')[0])
                if ($id -ge 89 -and $id -le 97) { $boardOverlay = $id }
            }
            if ($boardOverlay -ge 0) {
                $entry.Board = [int]$run.board_id
                if ($boardNames.ContainsKey($entry.Board)) { $entry.Name = $boardNames[$entry.Board] }
                $entry.Note = "overlay $boardOverlay"
            } else {
                # No board overlay: whatever board_id says, no board was loaded.
                $entry.Note = "aucun overlay de plateau (board_id=$($run.board_id), non concluant)"
            }
        }
    }
    $results += $entry
    Write-Output ("    -> board {0} ({1}), tour {2}, {3} frames, {4}" -f
        $entry.Board, $entry.Name, $entry.Turn, $entry.Frames, $entry.Result)
}

# ---- the answer ----
$lines = New-Object Collections.Generic.List[string]
function Emit([string]$t) { $lines.Add($t); Write-Output $t }
Emit ''
Emit '# Quels plateaux un singe atteint-il seul ?'
Emit ''
Emit ("{0} graines, {1} s chacune, lancees le {2}. Aucun prefixe d'approche : le" -f
    $Seeds.Count, $Seconds, $started.ToString('yyyy-MM-dd HH:mm'))
Emit "singe part du demarrage et doit traverser les menus lui-meme."
Emit ''
Emit '| graine | plateau | nom | tour | frames | transitions | resultat | mini-jeux | preuve |'
Emit '|---|---|---|---|---|---|---|---|---|'
foreach ($r in $results) {
    Emit ('| {0} | {1} | {2} | {3} | {4} | {5} | {6} | {7} | {8} |' -f
        $r.Seed, $r.Board, $r.Name, $r.Turn, $r.Frames, $r.Overlays, $r.Result,
        ($r.Minigames -join ' '), $r.Note)
}
$reached = @($results | Where-Object { $_.Board -ge 0 })
$distinct = @($reached | ForEach-Object { $_.Board } | Sort-Object -Unique)
Emit ''
Emit ("**{0} graines sur {1} ont atteint un plateau.** Plateaux distincts : {2}" -f
    $reached.Count, $results.Count, $(if ($distinct.Count) { $distinct -join ', ' } else { 'aucun' }))
Emit ''
Emit 'Tout ce qui est atteint ici reste `SCRIPTED` et plafonne a `PARTIAL`.'

$target = Resolve-SurveyPath $ResultFile
New-Item -ItemType Directory -Path (Split-Path $target -Parent) -Force | Out-Null
[IO.File]::WriteAllLines($target, $lines)
Write-Output ''
Write-Output "ecrit dans $target"

if ($reached.Count -eq 0) { exit 1 }
exit 0
